FROM ubuntu:latest

# Change the GitHub link to another one if you need

RUN \
  apt-get update && \
  apt-get -y upgrade

RUN \
  apt-get -y install python3 && \
  apt-get -y install python3-pip

RUN apt-get -y install git

RUN pip install git+https://github.com/fatjonfreskina/test-script-python-setup
# ENTRYPOINT [ "test" ]

CMD ["/bin/bash"]