FROM python:3

WORKDIR /zone

# Change the GitHub link to another one if you need

RUN pip install git+https://github.com/fatjonfreskina/test-script-python-setup 
   
ENTRYPOINT [ "test" ]

# This works fine!
